### ISSUE TITLE
Running chess as a gym environment

### ISSUE THREAD

**Issue by achaiah** [MeltingShoe/gym-chess#2]
Running into errors trying to execute sample code in the README using python3.6:
```
import gym
import gym_chess

env = gym.make('chess-v0')
env.render()
```
with the error being:
```
>>> env = gym.make('chess-v0')
WARN: Environment '<class 'gym_chess.envs.chess_env.ChessEnv'>' has deprecated methods. Compatibility code invoked.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/gym/envs/registration.py", line 163, in make
    return registry.make(id)
  File "/opt/conda/lib/python3.6/site-packages/gym/envs/registration.py", line 121, in make
    patch_deprecated_methods(env)
  File "/opt/conda/lib/python3.6/site-packages/gym/envs/registration.py", line 181, in patch_deprecated_methods
    env.seed  = env._seed
AttributeError: 'ChessEnv' object has no attribute '_seed'
```

**Comment by MeltingShoe** [comment]
This is an issue with the version of gym. To fix it run 

`pip uninstall gym`

`pip install -Iv gym==0.9.4`
